### PR TITLE
added cinnabuns

### PR DESCRIPTION
**Pull request by lazybuggy**
Added cinnabons to the list for issue #8

### CODE REVIEW

**Comment by vsoch** [comment]
ahh I love cinnamon buns how did you know! Haha.

Is there a good picture around that is served with https?

**Review by vsoch — CHANGES_REQUESTED** [review]
This must be added! Let's find a https image first.

**Comment by lazybuggy** [comment]
haha who doesnt! i'll look for a https image now

**Comment by vsoch** [comment]
We should definitely find one that is more square with a white background (akin to the first with https!) This one will render strange in the main page (the same thing happened with the white bread and I went back and downloaded and cropped the image)

**Comment by vsoch** [comment]
Totally nailed it! :yum: 

Once more check - so the price of a single Cinnabon is about $1.90, so you get 21 for 40? Around here it's more like $2.80 (and change) so you could get ~14 or so.

**Comment by lazybuggy** [comment]
i didn't realize thsts what the number meant haha. 👍 thanks :) .

**Review by vsoch — APPROVED** [review]

**Pull request merged**
