### PR TITLE
Add LED light bulb

### PR DESCRIPTION
**Pull request by bthieu**
Another item from me. It seems that I get all 5 pull requests from your repos.
Hope you don't mind :)
It is fine if I can't get the T shirt this way, I just want to play around .
Many thanks for making this issue. You are right, it was fun.

### CODE REVIEW

**Comment by vsoch** [comment]
Definitely! Could you please find a single light bulb so it makes sense to render it more than once or twice? (this is a bulk pack). Also, any reason you deleted one of the previous ones?

**Comment by bthieu** [comment]
Yes, I've found another link for single light bulb. Now I am trying to update the item.
No, I didn't mean to delete anything, I'm just confuse with all the pulling , resolving, ... process. May be I deleted something by mistake.

**Review by vsoch — CHANGES_REQUESTED** [review]
Much better, we are almost there!

 - the cost is $10, so you would only be able to get number: 4
 - Could you re-add the bluetooth-banana-phone? It looks like your branch deleted it.

**Comment by bthieu** [comment]
I was trying to resolve the conflict, it seems doing that will bring back the bluetooth-banana-phone. However the check is failed anyways. I have no ideas what to do next. 
So please just ignore this request. Thank you anyways.

**Comment by vsoch** [comment]
hey don't give up, you almost got it! You know, I'm here to help you if you get frustrated. The image issue is because they likely don't want you to embed the Amazon photo, but we can find another one! Let me see what I can do to finish this up.

**Review by vsoch — APPROVED** [review]

**Comment by vsoch** [comment]
Done! https://vsoch.github.io/40-avocados/led-light-bulb/

**Comment by bthieu** [comment]
Oh, so using another image can solve the problem, I was afraid that I broke something again. 
Thanks for helping me out (thumb up).

**Pull request merged**
