### PR TITLE
Add bread to things.yml

### PR DESCRIPTION
**Pull request by m4tty-d**

### CODE REVIEW

**Comment by vsoch** [comment]
That's a lot of bread :) Should we say the title is something specific like `sliced-white-bread-loaves` so others that want to contribute (other kinds of bread) can also do so? Choose whatever name you think is fitting!

**Comment by vsoch** [comment]
But actually I'm okay with just bread too :) Let me know your preference!

**Comment by m4tty-d** [comment]
Yes, good point. I think your suggestion will be good. Should I commit the necessary changes?

**Comment by vsoch** [comment]
I just updated! It's hard to keep up with  the number of PRs coming in, haha, apologies for the delay we will get the bread in :)

**Comment by vsoch** [comment]
I wound up needing to edit the graphic, it was way too tall! But looks good now :) https://vsoch.github.io/40-avocados/white-bread/ Thanks again!

**Pull request merged**
