### PR TITLE
Add NIKE socks

### PR DESCRIPTION
**Pull request by NeboCode**

### CODE REVIEW

**Comment by vsoch** [comment]
haha this one is good! Could we find a picture of either a single sock or a pair, and then update the quantity? The picture will be replicated N times (e.g., 12) so based on the picture you chose that would imply getting 72 socks (but the price would only be for 2 of the picture, 2 sets of 6).

**Comment by NeboCode** [comment]
Perhaps this one? https://cdn.shopify.com/s/files/1/2082/9501/products/SX6842-100_2_900x.jpg

**Comment by vsoch** [comment]
Yes perfect! The PR will need a rebase with master, and then double check that the price makes sense with the quantity.

**Review by vsoch — CHANGES_REQUESTED** [review]
Checks to do:

 - update to rebase with master, if needed
 - update image to single sock
 - make sure that quantityof socks (pairs?) is logical to add up to $40

**Pull request closed without merging**
