### PR TITLE
Added dumplings to things.yml

### PR DESCRIPTION
**Pull request by suyasha0**
#8

### CODE REVIEW

**Review by vsoch — CHANGES_REQUESTED** [review]
Yes!! Can you find a picture of a single dumpling? Since the interface will render 128 of those pictures.

**Comment by suyasha0** [comment]
done

**Review by vsoch — APPROVED** [review]

**Comment by vsoch** [comment]
okay! We can try this one - if the page hiccups because it's huge I can try downsizing it, or maybe find a smaller one.

**Comment by vsoch** [comment]
This makes me hungry! https://vsoch.github.io/40-avocados/dumplings/

**Comment by suyasha0** [comment]
Wow looks yummy ! Yay :100:

**Pull request merged**
