### PR TITLE
129* of arguably the best card on Yugioh

### PR DESCRIPTION
**Pull request by HenryFilho**
(Actually it's a meme card, it's bad, really.)

### CODE REVIEW

**Comment by vsoch** [comment]
How do you know the price on this guy? I'm a bit worried about rendering the image 4k times, have you tried it?

**Comment by HenryFilho** [comment]
I've found it on amazon for 1 cent. (Maybe it's a scam because there's also a guy selling it for 31 cent only, also on amazon. I guess rendering 129 times is safer so i'll modify that.)

**Comment by vsoch** [comment]
haha ye s good call! A few more tweaks:

 - could you please update the image to be of the card itself? 
 - For the name, could you be specific like `yugioh-playig-card-snapesnatch` (no caps)

Thanks!

**Comment by HenryFilho** [comment]
Did it!

**Comment by vsoch** [comment]
Haha ok, we will just ignore the 3.99 shipping and handling :)

**Pull request merged**
