### PR TITLE
Update things.yml

### PR DESCRIPTION
**Pull request by gowtham1997**
added Edifier H840 Audiophile Over-The-Ear Headphone

### CODE REVIEW

**Comment by vsoch** [comment]
This LGTM! Would you mind changing `Edifier H840 Audiophile Over-The-Ear Headphone:` to be a simplier `over-the-ear-headphone:` (and note also making all lowercase, removing spaces since we create folders)

**Comment by gowtham1997** [comment]
Done @vsoch

**Comment by vsoch** [comment]
It seems to be having trouble with the image - if you add it to the repo we can be sure this doesn't cause issue in the future! You can download it, add to the docs/img folder (rename to correspond with the title) and then in the link just put `https://vsoch.github.io/40-avocados/img/<name-of-image.jpg>` or similar.

**Comment by gowtham1997** [comment]
@vsoch all checks have passed

**Comment by vsoch** [comment]
This should be good to go!

**Pull request merged**
