### PR TITLE
Add Masrhmallows

### PR DESCRIPTION
**Pull request by bthieu**
This is just a random brand, hope that they are good :)

### CODE REVIEW

**Comment by vsoch** [comment]
haha yes!!

Did you mean to delete pencils?

**Comment by bthieu** [comment]
oh, no, I didn't mean that, somehow the pencils gone. I guess I did something wrong.

**Comment by vsoch** [comment]
Let me see if I can help out :)

**Comment by bthieu** [comment]
I see you've solved that, thanks.

**Comment by vsoch** [comment]
np! Huge +1 on marshmallows, thanks for the PR!

**Pull request closed without merging**
