### PR TITLE
Added wireless mice

### PR DESCRIPTION
**Pull request by sometallgit**

### CODE REVIEW

**Comment by vsoch** [comment]
These ssl amazon images are for some reason consistently failing the check! See if you can find one that can be embedded in an external page.

**Review by vsoch — CHANGES_REQUESTED** [review]
Find an image (or add to repo in docs/img) that passes requests.head(url) check. See the others in the things.yml linking to this repo for examples.

**Comment by sometallgit** [comment]
I have added a downloaded version of the image into the repo :)

**Comment by vsoch** [comment]
Looks good! Will merge when CI passes.

**Review by vsoch — APPROVED** [review]

**Comment by vsoch** [comment]
Thanks for your contribution! Merging.

**Pull request merged**
